### PR TITLE
Set show checkboxes to true on create:controller

### PR DESCRIPTION
**Pull request by neilcarpenter1**

### CODE REVIEW

**Comment by neilcarpenter1** [comment]
I think that because we have an onDelete method available to us, it would be ideal to display a delete button and show checkboxes on backend lists by default when using php artisan create:controller

**Comment by LukeTowers** [comment]
Why'd you close it?

**Comment by neilcarpenter1** [comment]
Because i merged in the develop branch - would that still be ok?

**Comment by LukeTowers** [comment]
Ah, gotcha. Yeah, don't add merge commits if you can help it, but if not I'll just squash the PR when I merge it into core. So not a big problem

**Comment by neilcarpenter1** [comment]
@LukeTowers would I be best off creating a new pull request without the merged commits?

**Comment by LukeTowers** [comment]
Yep

**Pull request closed without merging**
