### PR TITLE
Change asset compiling

### PR DESCRIPTION
**Pull request by christianWilling**
hi this is the scss filter https://github.com/octobercms/october/pull/2180 i hope this work for you

### CODE REVIEW

**Comment by daftspunk** [comment]
We had some issues with the leafo/less package because it was no longer being maintained, the `oyejorge/less.php` package appears to work better. Refs: https://github.com/octobercms/october/issues/179

Is it possible to adapt this code to the oyejorge package instead?

**Comment by daftspunk** [comment]
Please make sure your PRs are submitted to the `develop` branch.

**Comment by christianWilling** [comment]
yes i have created an new pr https://github.com/octobercms/library/pull/225

**Comment by amdad** [comment]
Thanks for this!

What about including optionally _compass_ to use in theme? What will be the easiest way to do this in new compiler?

**Comment by christianWilling** [comment]
hi compass isn't installed on the most server thats the reason why it should work in php

**Comment by amdad** [comment]
Yes, I just ask about this PHP implementation. What will be the easiest way to have this in October since SCSS finally be in core. Will you write some plugin if I ask nicely? :) Or some other way, to import compass elements. Modularity is also important. Don't need to have all at once.

**Comment by amdad** [comment]
@christianWilling ping you to check this topic.

**Comment by daftspunk** [comment]
Compass can be included manually in SCSS as far as I know. Have a look at this project here for an example:

https://github.com/daftspunk/utility/tree/1.0-stable/scss/frameworks

Note the `_compass.scss` file, it is probably an older version but it works.

**Comment by amdad** [comment]
Thank U!

**Pull request closed without merging**
