### PR TITLE
unicode character in slugs

### PR DESCRIPTION
**Pull request by sajjad-ser**
please support Unicode characters in slugs and urls

### CODE REVIEW

**Comment by daftspunk** [comment]
Why does Laravel not do this? Also this needs unit tests.

**Comment by sajjad-ser** [comment]
I sent a pull request in laravel. they told me if i want to do this i can extend the class for my self.
I will do this modification in persian plugin and use it in my projects with no problem.

**Comment by LukeTowers** [comment]
@sajjad-ser Are you willing to put together a unit test for this so we could merge it? If not, let me know

**Comment by daftspunk** [comment]
Laravel appear to have fixed this in v5.5, which we are upgrading to soon. 

```
Str::slug('foo bar', 'en');
```

**Pull request closed without merging**
