### PR TITLE
Add fromData() method

### PR DESCRIPTION
**Pull request by alxy**
This is the easiest implementation possible, however it requires a temporary file to be created. It can be discussed, if there is a need to delete the file afterwards explicitly.

### CODE REVIEW

**Comment by LukeTowers** [comment]
If we go the temp file route, then we'll need to unlink it afterwards to remove it immediately afterwards. Something like

```php
$path = //create temp file;
$file = $this->fromPath($path);
unlink($path);
return $file;
```

Have you looked into using the PHP IO streams instead for this? http://php.net/manual/en/wrappers.php.php

**Comment by alxy** [comment]
I added a commit to delete the temporary file.

**Comment by LukeTowers** [comment]
That doesn't delete it, that just removes the reference to it in PHP.

**Comment by alxy** [comment]
And this is why I should never commit untested code.  Yeah, I will test this first and then provide the correcting PR.

**Comment by LukeTowers** [comment]
Also, could you please look into using the PHP streams feature I linked? If we could use that instead we wouldn't even need to create a temporary file

**Pull request merged**
