### PR TITLE
Revert "Update StylesheetMinify"

### PR DESCRIPTION
**Pull request by Samuell1**
Reverts octobercms/library#361

### CODE REVIEW

**Comment by w20k** [comment]
@mjauvin - https://github.com/octobercms/october/issues/4040#issuecomment-452217962

**Comment by Samuell1** [comment]
@w20k i reverted it by this button, maybe this is a github issue?

obrazok

**Comment by LukeTowers** [comment]
@Samuell1 really we just need the newlines one and the 0 0 0 0 one gone, all the others with their descriptive comments are fine.

**Comment by w20k** [comment]
Fine - 'For now 😄'

**Comment by w20k** [comment]
Will be closing this PR as agreed with @Samuell1.

**Pull request closed without merging**
