### PR TITLE
Update GeneratorCommand.php

### PR DESCRIPTION
**Pull request by gpasztor87**
Do not throws an exception, if the file is exists.

### CODE REVIEW

**Comment by gpasztor87** [comment]
This is also prevent overwriting existing files, but allows generating other (missing) files in the command.

**Comment by LukeTowers** [comment]
But do we want the generator to continue generating files when it will be generating an incomplete set? @daftspunk any thoughts?

**Comment by daftspunk** [comment]
I think it generates all the files up until that point. I think there is a `--force` flag you can use to overcome this.

**Comment by LukeTowers** [comment]
@daftspunk Sounds like a good idea. @gpasztor87 Would that solve your problem?

**Comment by gpasztor87** [comment]
Yes, thank you.

**Pull request closed without merging**
