### PR TITLE
addPurgeable should use parent purgeable property

### PR DESCRIPTION
**Pull request by JoakimBo**
addPurgeable() used wrong purgeable property, should use parent->purgeable

### CODE REVIEW

**Comment by LukeTowers** [comment]
Why?

**Comment by LukeTowers** [comment]
This is in regards to octobercms/october#3428, closing.

**Comment by JoakimBo** [comment]
@LukeTowers Sorry for any inconvenience, this was a misunderstanding on my part.

**Comment by LukeTowers** [comment]
No worries! I appreciate the enthusiasm :)

**Pull request closed without merging**
