### PR TITLE
Fix searching in non text fields under Postgres (filters)

### PR DESCRIPTION
**Pull request by mplodowski**
This fixes searching in list filters under Postgres database.

Same issue as here: https://github.com/octobercms/october/pull/2092

### CODE REVIEW

**Comment by daftspunk** [comment]
Please clean the inconsistent code, it should be

```
DbDongle::cast($field, 'text')
```

Instead of

```
DbDongle::cast($field ,'text')
```

**Comment by mplodowski** [comment]
Fixed. Sorry, for this typo.

**Comment by LukeTowers** [comment]
@daftspunk What's left to merge this?

**Comment by daftspunk** [comment]
Looks alright. Thanks!

**Pull request merged**
