### PR TITLE
Make user model implement Authenticatable contract

### PR DESCRIPTION
**Pull request by SeriousKen**
Makes user model implement Illuminate\Contracts\Auth\Authenticatable, only adds one new method.

### CODE REVIEW

**Comment by LukeTowers** [comment]
See https://github.com/octobercms/library/tree/laravel-auth

**Comment by SeriousKen** [comment]
Hi @LukeTowers, thanks for pointing that branch out. Is there any reason this isn't merged in? Is there a way I can use this branch? I've tried to change my composer.json but it fails due to conflicting versions of the october/rain package. I really would like to use gates in the project I'm working on.

**Comment by SeriousKen** [comment]
Hi @LukeTowers figured it out. Thanks.

**Comment by LukeTowers** [comment]
@SeriousKen if you ever want to load a different branch from the library, use the `as 1.0` keyword in your requirements. It hasn't been merged yet because I haven't had the chance to properly test it yet, will do so shortly or if lots of people keep reminding me on slack.

**Comment by bennothommo** [comment]
@LukeTowers need some help with testing this out? I was hoping to have Authenticable in so I could have a crack at writing some unit tests for the Backend with authentication. It seems that Laravel's `actingAs` test method requires the model implement that contract.

**Comment by bennothommo** [comment]
@LukeTowers Great to hear. Nothing jumps to mind in terms of advice - if you're working on top of @daftspunk's branch, it looks like it covers all the necessary stuff pretty well. Let me know once it's ready and I'll be happy to give it a test and try implementing some test cases. :)

**Pull request closed without merging**
