### PR TITLE
Update to parseGroupConcat() function

### PR DESCRIPTION
**Pull request by briddle**
https://octobercms.com/forum/post/supporting-db-postgresql?page=1#post-26378

### CODE REVIEW

**Comment by w20k** [comment]
@briddle link your issue here as well.

**Comment by briddle** [comment]
> @briddle link your issue here as well.
> Could you also fix test ;)
> 
> Faild - DongleTest::testPgsqlParseGroupConcat

I would if I knew what I was doing. Unfortunately I do not...

**Comment by w20k** [comment]
@briddle will look at it then.

**Comment by LukeTowers** [comment]
This pull request has been made to the wrong branch. Please review [the contributing guidelines](https://github.com/octobercms/october/blob/master/.github/CONTRIBUTING.md#pull-requests) as all PRs need to be made to the develop branch.

I'll fix it for you this time, but please ensure you make any future PRs to the develop branch, not the master branch.

**Comment by w20k** [comment]
@briddle if you're still here could you post your raw query before `preg_replace`? 
We could merge this one, after confirmation. 
Also, could you add your PG version to the PR.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Pull request closed without merging**
