### PR TITLE
Make extendClassWith support dot notation

### PR DESCRIPTION
**Pull request by SeriousKen**
Currently `extendClassWith` throws an exception when you try to extend using dot notation supported in other methods. This patch fixes that inconsistency.

### CODE REVIEW

**Comment by LukeTowers** [comment]
Please add a test

**Comment by SeriousKen** [comment]
No problem @LukeTowers, I'll do that. I noticed that there are currently no tests covering dot notation in `ExtendableTest` so I'll look at covering those cases too.

**Comment by LukeTowers** [comment]
Awesome, thanks @SeriousKen! The more test coverage the better :)

**Comment by SeriousKen** [comment]
Trying to run `composer install` after cloning this repository so I can run the tests and I hit this:

  Problem 1
    - Installation request for swiftmailer/swiftmailer ~5.1 -> satisfiable by swiftmailer/swiftmailer[5.x-dev, v5.1.0, v5.2.0, v5.2.1, v5.2.2, v5.3.0, v5.3.1, v5.4.0, v5.4.1, v5.4.2, v5.4.3, v5.4.4, v5.4.5, v5.4.6, v5.4.7, v5.4.8].
    - illuminate/mail 5.5.x-dev requires swiftmailer/swiftmailer ~6.0 -> satisfiable by swiftmailer/swiftmailer[6.0.x-dev].
    - illuminate/mail v5.5.0 requires swiftmailer/swiftmailer ~6.0 -> satisfiable by swiftmailer/swiftmailer[6.0.x-dev].
    - illuminate/mail v5.5.16 requires swiftmailer/swiftmailer ~6.0 -> satisfiable by swiftmailer/swiftmailer[6.0.x-dev].
    - illuminate/mail v5.5.17 requires swiftmailer/swiftmailer ~6.0 -> satisfiable by swiftmailer/swiftmailer[6.0.x-dev].
    - illuminate/mail v5.5.2 requires swiftmailer/swiftmailer ~6.0 -> satisfiable by swiftmailer/swiftmailer[6.0.x-dev].
    - illuminate/mail v5.5.28 requires swiftmailer/swiftmailer ~6.0 -> satisfiab
le by swiftmailer/swiftmailer[6.0.x-dev].
    - Conclusion: don't install swiftmailer/swiftmailer 6.0.x-dev
    - Installation request for illuminate/mail 5.5.* -> satisfiable by illuminate/mail[5.5.x-dev, v5.5.0, v5.5.16, 5.5.17, v5.5.2, v5.5.28].

**Comment by LukeTowers** [comment]
@SeriousKen you may need to make a PR to update October's dependency version to ~6.0 https://github.com/laravel/framework/blob/5.5/src/Illuminate/Mail/composer.json#L23

**Comment by SeriousKen** [comment]
@LukeTowers finally got round to adding tests for this

**Comment by LukeTowers** [comment]
@SeriousKen so this is all read to go now?

**Comment by SeriousKen** [comment]
I think so. I had an issue with getting my branch up-to-date with develop, which I think I've resolved (there should only be two files updated) and the dot notation works.

**Pull request merged**
