### PR TITLE
Fire event after impersonate

### PR DESCRIPTION
**Pull request by rubenvanerk**
I would like to redirect after impersonating as per https://github.com/rainlab/user-plugin/issues/400.

### CODE REVIEW

**Comment by bennothommo** [comment]
@rubenvanerk It looks like `afterImpersonate` is already an event, fired here: https://github.com/octobercms/library/blob/807ae284a80f371d78f44b98ac141a1b26e81126/src/Auth/Manager.php#L742

You may need to call yours `impersonate` instead.

**Comment by rubenvanerk** [comment]
@bennothommo You're correct, changed the event name.

**Comment by LukeTowers** [comment]
@rubenvanerk why can't you use the existing events: https://github.com/octobercms/library/commit/dc5952d5b010602116012383ae9f1c6bf02d9182? Also @bennothommo we need to update the docs on those, I copy pasted them from model.afterBoot it looks like

**Comment by LukeTowers** [comment]
Provided an alternative solution https://github.com/rainlab/user-plugin/issues/400#issuecomment-528925399

**Pull request closed without merging**
