### PR TITLE
are deferred providers being deferred?

### PR DESCRIPTION
**Pull request by rajakhoury**
I am not sure if the service providers are being really deferred but I believe they are not. The assumption is based on the following;

- `$defer` property is deprecated [[doc]](https://laravel.com/docs/5.8/upgrade#deferred-service-providers) and cannot find any definition / fallback in `Illuminate\Support\ServiceProvider` 
- A provider is considered deferred if it is an instance of `DeferrableProvider`. See `isDeferred()`
- Tracing back to `\Illuminate\Foundation\ProviderRepository::compileManifest()` here is how it is generated and we can assume deferred providers will be pushed into the `deferred` array key of the manifest;

            // When recompiling the service manifest, we will spin through each of the
            // providers and check if it's a deferred provider or not. If so we'll
            // add it's provided services to the manifest and note the provider.
            if ($instance->isDeferred()) {
                foreach ($instance->provides() as $service) {
                    $manifest['deferred'][$service] = $provider;
                }

                $manifest['when'][$provider] = $instance->when();
            }

            // If the service providers are not deferred, we will simply add it to an
            // array of eagerly loaded providers that will get registered on every
            // request to this application instead of "lazy" loading every time.
            else {
                $manifest['eager'][] = $provider;
            }
- The services manifest located in `storage/framework/services.php` show the opposite ( eager loaded).
- Affected Providers : Flash, HTML, Network, Parse, Scaffold

Manifest before changes:
````
<?php return array (
  'providers' => 
  array (
    0 => 'Illuminate\\Broadcasting\\BroadcastServiceProvider',
    1 => 'Illuminate\\Bus\\BusServiceProvider',
    2 => 'Illuminate\\Cache\\CacheServiceProvider',
    3 => 'Illuminate\\Cookie\\CookieServiceProvider',
    4 => 'Illuminate\\Encryption\\EncryptionServiceProvider',
    5 => 'Illuminate\\Foundation\\Providers\\FoundationServiceProvider',
    6 => 'Illuminate\\Hashing\\HashServiceProvider',
    7 => 'Illuminate\\Pagination\\PaginationServiceProvider',
    8 => 'Illuminate\\Pipeline\\PipelineServiceProvider',
    9 => 'Illuminate\\Queue\\QueueServiceProvider',
    10 => 'Illuminate\\Session\\SessionServiceProvider',
    11 => 'Illuminate\\Validation\\ValidationServiceProvider',
    12 => 'Illuminate\\View\\ViewServiceProvider',
    13 => 'Jenssegers\\Date\\DateServiceProvider',
    14 => 'Laravel\\Tinker\\TinkerServiceProvider',
    15 => 'Carbon\\Laravel\\ServiceProvider',
    16 => 'Laravel\\Tinker\\TinkerServiceProvider',
    17 => 'October\\Rain\\Foundation\\Providers\\ConsoleSupportServiceProvider',
    18 => 'October\\Rain\\Database\\DatabaseServiceProvider',
    19 => 'October\\Rain\\Halcyon\\HalcyonServiceProvider',
    20 => 'October\\Rain\\Filesystem\\FilesystemServiceProvider',
    21 => 'October\\Rain\\Parse\\ParseServiceProvider',
    22 => 'October\\Rain\\Html\\HtmlServiceProvider',
    23 => 'October\\Rain\\Html\\UrlServiceProvider',
    24 => 'October\\Rain\\Network\\NetworkServiceProvider',
    25 => 'October\\Rain\\Scaffold\\ScaffoldServiceProvider',
    26 => 'October\\Rain\\Flash\\FlashServiceProvider',
    27 => 'October\\Rain\\Mail\\MailServiceProvider',
    28 => 'October\\Rain\\Argon\\ArgonServiceProvider',
    29 => 'October\\Rain\\Redis\\RedisServiceProvider',
    30 => 'System\\ServiceProvider',
  ),
  'eager' => 
  array (
    0 => 'Illuminate\\Cookie\\CookieServiceProvider',
    1 => 'Illuminate\\Encryption\\EncryptionServiceProvider',
    2 => 'Illuminate\\Foundation\\Providers\\FoundationServiceProvider',
    3 => 'Illuminate\\Pagination\\PaginationServiceProvider',
    4 => 'Illuminate\\Session\\SessionServiceProvider',
    5 => 'Illuminate\\View\\ViewServiceProvider',
    6 => 'Jenssegers\\Date\\DateServiceProvider',
    7 => 'Laravel\\Tinker\\TinkerServiceProvider',
    8 => 'Carbon\\Laravel\\ServiceProvider',
    9 => 'Laravel\\Tinker\\TinkerServiceProvider',
    10 => 'October\\Rain\\Foundation\\Providers\\ConsoleSupportServiceProvider',
    11 => 'October\\Rain\\Database\\DatabaseServiceProvider',
    12 => 'October\\Rain\\Halcyon\\HalcyonServiceProvider',
    13 => 'October\\Rain\\Filesystem\\FilesystemServiceProvider',
    14 => 'October\\Rain\\Parse\\ParseServiceProvider',
    15 => 'October\\Rain\\Html\\HtmlServiceProvider',
    16 => 'October\\Rain\\Html\\UrlServiceProvider',
    17 => 'October\\Rain\\Network\\NetworkServiceProvider',
    18 => 'October\\Rain\\Scaffold\\ScaffoldServiceProvider',
    19 => 'October\\Rain\\Flash\\FlashServiceProvider',
    20 => 'October\\Rain\\Argon\\ArgonServiceProvider',
    21 => 'System\\ServiceProvider',
  ),
  'deferred' => 
  array (
    'Illuminate\\Broadcasting\\BroadcastManager' => 'Illuminate\\Broadcasting\\BroadcastServiceProvider',
    'Illuminate\\Contracts\\Broadcasting\\Factory' => 'Illuminate\\Broadcasting\\BroadcastServiceProvider',
    'Illuminate\\Contracts\\Broadcasting\\Broadcaster' => 'Illuminate\\Broadcasting\\BroadcastServiceProvider',
    'Illuminate\\Bus\\Dispatcher' => 'Illuminate\\Bus\\BusServiceProvider',
    'Illuminate\\Contracts\\Bus\\Dispatcher' => 'Illuminate\\Bus\\BusServiceProvider',
    'Illuminate\\Contracts\\Bus\\QueueingDispatcher' => 'Illuminate\\Bus\\BusServiceProvider',
    'cache' => 'Illuminate\\Cache\\CacheServiceProvider',
    'cache.store' => 'Illuminate\\Cache\\CacheServiceProvider',
    'cache.psr6' => 'Illuminate\\Cache\\CacheServiceProvider',
    'memcached.connector' => 'Illuminate\\Cache\\CacheServiceProvider',
    'hash' => 'Illuminate\\Hashing\\HashServiceProvider',
    'hash.driver' => 'Illuminate\\Hashing\\HashServiceProvider',
    'Illuminate\\Contracts\\Pipeline\\Hub' => 'Illuminate\\Pipeline\\PipelineServiceProvider',
    'queue' => 'Illuminate\\Queue\\QueueServiceProvider',
    'queue.worker' => 'Illuminate\\Queue\\QueueServiceProvider',
    'queue.listener' => 'Illuminate\\Queue\\QueueServiceProvider',
    'queue.failer' => 'Illuminate\\Queue\\QueueServiceProvider',
    'queue.connection' => 'Illuminate\\Queue\\QueueServiceProvider',
    'validator' => 'Illuminate\\Validation\\ValidationServiceProvider',
    'validation.presence' => 'Illuminate\\Validation\\ValidationServiceProvider',
    'mailer' => 'October\\Rain\\Mail\\MailServiceProvider',
    'swift.mailer' => 'October\\Rain\\Mail\\MailServiceProvider',
    'swift.transport' => 'October\\Rain\\Mail\\MailServiceProvider',
    'Illuminate\\Mail\\Markdown' => 'October\\Rain\\Mail\\MailServiceProvider',
    'redis' => 'October\\Rain\\Redis\\RedisServiceProvider',
    'redis.connection' => 'October\\Rain\\Redis\\RedisServiceProvider',
  ),
);
````

And after:
````
<?php return array (
  'providers' => 
  array (
    0 => 'Illuminate\\Broadcasting\\BroadcastServiceProvider',
    1 => 'Illuminate\\Bus\\BusServiceProvider',
    2 => 'Illuminate\\Cache\\CacheServiceProvider',
    3 => 'Illuminate\\Cookie\\CookieServiceProvider',
    4 => 'Illuminate\\Encryption\\EncryptionServiceProvider',
    5 => 'Illuminate\\Foundation\\Providers\\FoundationServiceProvider',
    6 => 'Illuminate\\Hashing\\HashServiceProvider',
    7 => 'Illuminate\\Pagination\\PaginationServiceProvider',
    8 => 'Illuminate\\Pipeline\\PipelineServiceProvider',
    9 => 'Illuminate\\Queue\\QueueServiceProvider',
    10 => 'Illuminate\\Session\\SessionServiceProvider',
    11 => 'Illuminate\\Validation\\ValidationServiceProvider',
    12 => 'Illuminate\\View\\ViewServiceProvider',
    13 => 'Jenssegers\\Date\\DateServiceProvider',
    14 => 'Laravel\\Tinker\\TinkerServiceProvider',
    15 => 'Carbon\\Laravel\\ServiceProvider',
    16 => 'Laravel\\Tinker\\TinkerServiceProvider',
    17 => 'October\\Rain\\Foundation\\Providers\\ConsoleSupportServiceProvider',
    18 => 'October\\Rain\\Database\\DatabaseServiceProvider',
    19 => 'October\\Rain\\Halcyon\\HalcyonServiceProvider',
    20 => 'October\\Rain\\Filesystem\\FilesystemServiceProvider',
    21 => 'October\\Rain\\Parse\\ParseServiceProvider',
    22 => 'October\\Rain\\Html\\HtmlServiceProvider',
    23 => 'October\\Rain\\Html\\UrlServiceProvider',
    24 => 'October\\Rain\\Network\\NetworkServiceProvider',
    25 => 'October\\Rain\\Scaffold\\ScaffoldServiceProvider',
    26 => 'October\\Rain\\Flash\\FlashServiceProvider',
    27 => 'October\\Rain\\Mail\\MailServiceProvider',
    28 => 'October\\Rain\\Argon\\ArgonServiceProvider',
    29 => 'October\\Rain\\Redis\\RedisServiceProvider',
    30 => 'System\\ServiceProvider',
  ),
  'eager' => 
  array (
    0 => 'Illuminate\\Cookie\\CookieServiceProvider',
    1 => 'Illuminate\\Encryption\\EncryptionServiceProvider',
    2 => 'Illuminate\\Foundation\\Providers\\FoundationServiceProvider',
    3 => 'Illuminate\\Pagination\\PaginationServiceProvider',
    4 => 'Illuminate\\Session\\SessionServiceProvider',
    5 => 'Illuminate\\View\\ViewServiceProvider',
    6 => 'Jenssegers\\Date\\DateServiceProvider',
    7 => 'Laravel\\Tinker\\TinkerServiceProvider',
    8 => 'Carbon\\Laravel\\ServiceProvider',
    9 => 'Laravel\\Tinker\\TinkerServiceProvider',
    10 => 'October\\Rain\\Foundation\\Providers\\ConsoleSupportServiceProvider',
    11 => 'October\\Rain\\Database\\DatabaseServiceProvider',
    12 => 'October\\Rain\\Halcyon\\HalcyonServiceProvider',
    13 => 'October\\Rain\\Filesystem\\FilesystemServiceProvider',
    14 => 'October\\Rain\\Html\\UrlServiceProvider',
    15 => 'October\\Rain\\Argon\\ArgonServiceProvider',
    16 => 'System\\ServiceProvider',
  ),
  'deferred' => 
  array (
    'Illuminate\\Broadcasting\\BroadcastManager' => 'Illuminate\\Broadcasting\\BroadcastServiceProvider',
    'Illuminate\\Contracts\\Broadcasting\\Factory' => 'Illuminate\\Broadcasting\\BroadcastServiceProvider',
    'Illuminate\\Contracts\\Broadcasting\\Broadcaster' => 'Illuminate\\Broadcasting\\BroadcastServiceProvider',
    'Illuminate\\Bus\\Dispatcher' => 'Illuminate\\Bus\\BusServiceProvider',
    'Illuminate\\Contracts\\Bus\\Dispatcher' => 'Illuminate\\Bus\\BusServiceProvider',
    'Illuminate\\Contracts\\Bus\\QueueingDispatcher' => 'Illuminate\\Bus\\BusServiceProvider',
    'cache' => 'Illuminate\\Cache\\CacheServiceProvider',
    'cache.store' => 'Illuminate\\Cache\\CacheServiceProvider',
    'cache.psr6' => 'Illuminate\\Cache\\CacheServiceProvider',
    'memcached.connector' => 'Illuminate\\Cache\\CacheServiceProvider',
    'hash' => 'Illuminate\\Hashing\\HashServiceProvider',
    'hash.driver' => 'Illuminate\\Hashing\\HashServiceProvider',
    'Illuminate\\Contracts\\Pipeline\\Hub' => 'Illuminate\\Pipeline\\PipelineServiceProvider',
    'queue' => 'Illuminate\\Queue\\QueueServiceProvider',
    'queue.worker' => 'Illuminate\\Queue\\QueueServiceProvider',
    'queue.listener' => 'Illuminate\\Queue\\QueueServiceProvider',
    'queue.failer' => 'Illuminate\\Queue\\QueueServiceProvider',
    'queue.connection' => 'Illuminate\\Queue\\QueueServiceProvider',
    'validator' => 'Illuminate\\Validation\\ValidationServiceProvider',
    'validation.presence' => 'Illuminate\\Validation\\ValidationServiceProvider',
    'parse.markdown' => 'October\\Rain\\Parse\\ParseServiceProvider',
    'parse.yaml' => 'October\\Rain\\Parse\\ParseServiceProvider',
    'parse.twig' => 'October\\Rain\\Parse\\ParseServiceProvider',
    'parse.ini' => 'October\\Rain\\Parse\\ParseServiceProvider',
    'html' => 'October\\Rain\\Html\\HtmlServiceProvider',
    'form' => 'October\\Rain\\Html\\HtmlServiceProvider',
    'block' => 'October\\Rain\\Html\\HtmlServiceProvider',
    'network.http' => 'October\\Rain\\Network\\NetworkServiceProvider',
    'command.create.plugin' => 'October\\Rain\\Scaffold\\ScaffoldServiceProvider',
    'command.create.model' => 'October\\Rain\\Scaffold\\ScaffoldServiceProvider',
    'command.create.controller' => 'October\\Rain\\Scaffold\\ScaffoldServiceProvider',
    'command.create.component' => 'October\\Rain\\Scaffold\\ScaffoldServiceProvider',
    'command.create.formwidget' => 'October\\Rain\\Scaffold\\ScaffoldServiceProvider',
    'command.create.command' => 'October\\Rain\\Scaffold\\ScaffoldServiceProvider',
    'flash' => 'October\\Rain\\Flash\\FlashServiceProvider',
    'mailer' => 'October\\Rain\\Mail\\MailServiceProvider',
    'swift.mailer' => 'October\\Rain\\Mail\\MailServiceProvider',
    'swift.transport' => 'October\\Rain\\Mail\\MailServiceProvider',
    'Illuminate\\Mail\\Markdown' => 'October\\Rain\\Mail\\MailServiceProvider',
    'redis' => 'October\\Rain\\Redis\\RedisServiceProvider',
    'redis.connection' => 'October\\Rain\\Redis\\RedisServiceProvider',
  )
);
````

additional notes;
- Migrated singletons registration to the property (this is subjective as I find it cleaner)
- Removal of the Translation provider (no usage?) because the singletongs are being registered in `October\Rain\Foundation\Bootstrap\LoadTranslation`
- There might be more service providers to change if the current asumption is correct.

### CODE REVIEW

**Comment by bennothommo** [comment]
@rajakhoury Can you please pull the latest changes from our `wip/laravel-6` branch into your branch so that it hides the changes from your previous PRs that have already been merged?

**Comment by bennothommo** [comment]
@rajakhoury you'll also need to restore the Translation service provider. Whilst it is not in use directly with October, I believe it is made available as a subpackage.

**Comment by rajakhoury** [comment]
@bennothommo please bear with me as I have no idea what I'm doing 👀

sure I will restore the Translation provider.

**Comment by bennothommo** [comment]
@rajakhoury Thanks for that. Looks good to me.

**Comment by rajakhoury** [comment]
@bennothommo glad it helps. Thank you all for the great work

**Pull request merged**
