### PR TITLE
Fix escaping of multiline values in INI

### PR DESCRIPTION
**Pull request by Fl0Cri**
Fixes https://github.com/rainlab/pages-plugin/issues/327

I've added a test case to demonstrate the problem but I could not install composer dependencies on php 7.0.6 (need 7.0.8) so I didn't run it to check.

### CODE REVIEW

**Comment by LukeTowers** [comment]
Could you update your PHP to run the tests?

**Comment by Fl0Cri** [comment]
Okay, I'm on an other pc and I could run the tests.
- It's ok on Windows with php 7.1.7
- But on linux (using wsl) with php 7.1.11, I get an error telling me that the test fail, despite that both arrays are equals!? Have you already seen this?
```
1) IniTest::testMultilinesValues
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     'var' => '\Test\Path\'
     'editorContent' => '<p>Some
         <br>"Multi-line"
         <br>text
     </p>'
 )
```

**Comment by Fl0Cri** [comment]
Just installed and tested with php 7.2.2 on Windows, the test passes so it's maybe related to wsl or to a php bug in 7.1.11

**Comment by LukeTowers** [comment]
@Fl0Cri have you tried testing it on anything else?

**Comment by Fl0Cri** [comment]
I just found what's going wrong with my tests: Because the repo was cloned on Windows, git wrote everything with CRLF line endings to the filesystem.

The parse method run on Windows was also outputing line endings as CRLF so the test passes, but when run from linux it is outputing LF. The diff viewer of phpunit doesn't see that so it tells that both array are equals despite that the test is failing.

So if you clone the from a Linux Git on a Linux filesystem an run with a Linux environment everything should be ok.

**Comment by LukeTowers** [comment]
Would there be an issue with forcing both to use the same EOL character when testing it so that this doesn't happen to anyone else? It's a tricky thing that might be difficult to catch by someone unaware of its existence; so I think it might be better if we can change the test so that this can't happen.

**Comment by Fl0Cri** [comment]
Ok, the tests are passing now on my environment.

**Comment by LukeTowers** [comment]
So the PR is now complete? Does it still fix the original issue? @Fl0Cri

**Comment by Fl0Cri** [comment]
Yes, I've put the fix on the prod website where I noticed the bug and it's running fine with it.
My users did a lot of content editing with static pages and had no problems.

**Comment by LukeTowers** [comment]
Awesome, thanks for your work on this!

**Pull request merged**
