### PR TITLE
Add 'fit' method to Resizer

### PR DESCRIPTION
**Pull request by Notuom**
New feature.

Allows the image to be resized in order to fit to a bounding box (*maximum* width and height) while keeping aspect ratio.

I had this use case and thought it would be common enough to warrant an addition to the library.

I couldn't find unit tests for this class so I didn't add any. Let me know if something else needs to be done in order for this to be accepted (documentation, OctoberCMS side, etc) and I'll be glad to do it.

### CODE REVIEW

**Comment by osmanzeki** [comment]
Interesting feature and I agree this comes up all the time in ecommerce/product listings where product image dimensions can vary widly.

**Comment by LukeTowers** [comment]
This pull request has been made to the wrong branch. Please review [the contributing guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#pull-requests) as all PRs need to be made to the develop branch.

I'll fix it for you this time, but please ensure you make any future PRs to the develop branch, not the master branch.

**Comment by LukeTowers** [comment]
It needs to be added to the documentation: http://octobercms.com/docs/database/attachments#viewing-attachments.

Ideally, could you create a unit test for this entire class?

**Comment by Notuom** [comment]
Whoops, sorry. I didn't look at the contributing guidelines, my bad. I'll try to look into adding unit tests and updating docs over the weekend.

**Comment by LukeTowers** [comment]
No worries, thanks for your work on this!

**Comment by Notuom** [comment]
I didn't get time to create unit tests this week-end in the end. This isn't the most straightforward class to test, given the nature of image manipulation. I looked into generating images using temp or in-memory files, but I wasn't sure  about how to assert expected results using those.

So I thought about maybe adding some image files (enough to trigger different use cases and validate results for each unit test) as fixtures. Basically, generate result files and assert that giving different parameters with different input files create the expected files. Of course, this could become a pain if something slightly changes in the way the images are generated or the backend library changes, but I don't see that happening often. It's just something to think about though, it's not as easy to maintain as text assertions for sure, but at least the features would be tested as opposed to now.

Thoughts? I just wanted to run the basic design by maintainers / contributors before doing it, since it'll probably take some time to implement.

**Comment by LukeTowers** [comment]
@Notuom I would be fine with fixture inputs and outputs being used; if we're changing how it's processed we can update the fixtures.

**Comment by Notuom** [comment]
In my last commit, I started implementing the tests for this class using the strategy mentioned earlier. I think I have a good base to create the test cases quickly enough. Next step will be to create test cases for a good amount of different parameters and create the fixtures using the current code for the assertion method. Feel free to take a look and comment.

However, I ran into a problem, so for the moment, I replaced the FileHelper::extension call in Resizer by a native PHP pathinfo() call (also pushed in my previous commit), since it was the only thing causing a problem. We could leave it like that (anyway, it's a very simple thing that shouldn't need an helper function really), but if we absolutely want to use the facade, then I presume we would have to setup the app during some unit tests like this one. For the moment, this isn't setup (there's an empty method in the TestCase class, I suppose this was planned way back when) and I'm not too sure where to start from. I looked at the Laravel repo for inspiration (https://github.com/laravel/laravel/blob/master/tests/CreatesApplication.php), but wasn't able to get it running quickly (I'm not a Laravel internals expert). I'd prefer to avoid doing that as it seems like a lot of bloat for something that is replaced easily, but if October maintainers think this is preferable, I can look into it.

For reference, I ran `php vendor/bin/phpunit tests` and got the following:

```
There was 1 error:

1) ResizerTest::testResizeAutoLandscape
Error: Class 'File' not found

.../library/src/Database/Attach/Resizer.php:423
.../library/tests/Database/Attach/ResizerTest.php:99
.../library/tests/Database/Attach/ResizerTest.php:77
```

I'll hopefully have some more time before too long to finish the tests.

**Comment by LukeTowers** [comment]
Awesome, thanks for your work on this so far! Lot of effort to implement the `fit` sizing mode; I appreciate your willingness to help improve the code base!

As far as pathinfo goes, I'm fine replacing the use of the FileHelper with that - makes more sense to me to do it that way

**Comment by Notuom** [comment]
I'm done adding unit tests to Resizer. I covered most of the code (89%), excluding:

* Invalid / exceptions / errors
    * GD not loaded
    * Invalid EXIF orientation
    * Sharpness below or above 100
    * Invalid MIME type when loading
    * Invalid 'mode' option
* Wrapper code
    * Static "open" function (which only calls constructor anyway)
    * setOption (never called)
* Edge cases
    * EXIF orientations 6, 3, 1 (8 is tested)
    * webp open / save
    * Interlacing
    * Cropping in landscape

I ended up adding a library to assert base on image pixel contents as a dev dependency because it seemed like a much safer way to compare images (allowing for a slight error in pixel parity) than md5ing the file like I was doing previously (kudos to its creator).

Let me know if you have any questions / suggestions.

**Comment by LukeTowers** [comment]
Awesome, thanks very much for doing all of that work @Notuom!

**Comment by yapsr** [comment]
@Notuom Could you describe how the result from this mode differs from the "auto" mode?

**Comment by Notuom** [comment]
From what I could see from your PR, yours is essentially the same as mine, except it takes the result and centers it inside a transparent png. Mine keeps the original extension and does not add transparency. My personal use case was to generate images in a table and print a PDF with logos and I had to make sure they all fit within the same area.

It's been a while so I don't remember the specifics of the 'auto' method, but if you look at its code, it determines what to use as a baseline (width or height) depending on the format (portrait / landscape) of the image, while the 'fit' one always ensures the resulting image fits inside the dimensions given. Sometimes the result might be the same, but I can assure you it's not always the case. Here's an example I extrapolated from the unit tests:

Original image is portrait: 26x35
portrait

`$this->resizer->resize(25, 50, ['mode' => 'fit']);`: results in **25x34** image. That *does* fit inside 25x50.
testresizefitportrait50

`$this->resizer->resize(25, 50, ['mode' => 'auto']);`: results in **37x50** image. That *doesn't* fit inside 25x50, it goes over the limit width.
testresizeautoportrait50

Using 'auto' didn't work for my purpose which was having images that had a **maximum** canvas size, as I described in the PR.

As for how to merge, I would prefer to get this one merged first because I did it way back in February and put a lot of effort into implementing the unit tests for the Resizer class, so it would make sense to reuse that framework if we're adding another method to the class. Maybe the logic could even be reused since it's basically the same sizing principle but centered inside a png?

By the way, @LukeTowers, is there a reason why it hasn't been reviewed yet, other than maybe not having the time to look at it closely / other priorities? Looking back at the comments it looks like I still didn't update the docs. I can take care of this quickly if that's all it's missing. Not saying that to complain as I had pretty much forgotten about it, just wondering.

**Comment by LukeTowers** [comment]
@Notuom the only reason it hasn't been merged yet was lack of time to review it. With so many requests for support all of the time the squeaky wheel ends up getting the grease 😄 

PR to the docs would be appreciated, I would merge this one first simply for all your work on the unit testing functionality alone. I've asked @daftspunk to fix the current build of the library and then I should be able to review this PR and hopefully get it merged in and then we can get @yapsr's PR merged in as well afterwards.

**Comment by Notuom** [comment]
@LukeTowers No worries, I figured it was lack of free time more than anything :). I'll try to add some docs for this. The resize modes aren't really documented in depth in the docs (only listed), so I'll try to see if I can add some short descriptions for each of them at the same time.

**Comment by LukeTowers** [comment]
@Notuom that would be fantastic! Thanks!

**Comment by Notuom** [comment]
@yapsr I can't merge my own PR and I'm not a maintainer of this repo, I only asked for this feature to get merged. I didn't get around to adding the docs for the other Resizer stuff yet though, but I don't think that's blocking this from getting merged (actually it would make sense for it to be approved/merged before documentation is updated imho).

**Comment by LukeTowers** [comment]
@Notuom actually it is just waiting for a PR with the documentation updates, sorry for the confusion

**Comment by Notuom** [comment]
OK, in that case I shall get to it soon and link back to this PR! Sorry for misunderstanding.

**Comment by Notuom** [comment]
Updated PR to fix merge conflicts. Added documentation PR: octobercms/docs#317. Please let me know if you need anything else!

**Comment by yapsr** [comment]
@Notuom Thanks! 
@LukeTowers Shall I create a new PR based on the develop branch to add my 'contain' mode ?

**Comment by LukeTowers** [comment]
@yapsr yes please. Include unit tests for it as well too please

**Pull request merged**
