### PR TITLE
Multiple fixes related to PR #543

### LINKED ISSUE #5479: Calling sync() twice on many-to-many relationship fails in the dev branch, works in 1.0
- OctoberCMS Build: Develop branch; tested with laravel 6.18.43 or 6.20.15
- PHP Version: 7.4.8
- Database Engine: MySql (also fails in SqLite)
- Plugins Installed: https://github.com/cjkpl/oc-sync-plugin (contains the test case)

### Description:
Having two models, e.g. Student and Lesson, and many to many relationship between them, calling sync() second time fails:
```
        $s = Student::first();
        $l = Lesson::first();

        $s->lessons()->sync([$l->id]);
        $s->lessons()->sync([$l->id]);
```

### Steps To Reproduce:
1. Install a test plugin prepared to demonstrate the issue: https://github.com/cjkpl/oc-sync-plugin.git
2. Run unit test on the plugin.
3. Observed behavior: will work on the 1.0 branch (with Laravel 5.x); will throw and error on dev branch (with Laravel 6.x).

### PR DESCRIPTION
**Pull request by mjauvin**
Related to #543 
- $attachedIdList should be an array/collection not an object
- Add fully qualified key names in newPivotQuery() to prevent conflicts.

Fixes https://github.com/octobercms/october/issues/5479#issuecomment-772704701

### CODE REVIEW

**Comment by mjauvin** [comment]
I introduced that bug in my last PR (https://github.com/octobercms/library/pull/543)

That should REALLY be added to the 1.1.2 release, otherwise we'll be in trouble...

**Comment by mjauvin** [comment]
@Teranode can you check if this PR resolves [your issues](https://github.com/octobercms/library/pull/543#issuecomment-748677293) ?

Thanks.

**Comment by LukeTowers** [comment]
@mjauvin can you add some tests for the issue?

**Comment by Denoder** [comment]
Does not fix the issue it's still the same, I even tried just doing:

```php
    /**
     * Create a new query builder for the pivot table.
     *
     * This is an extension of Laravel's `newPivotQuery` method that allows `belongsToMany` and `morphToMany` relations
     * to have conditions.
     *
     * @return \Illuminate\Database\Query\Builder
     */
    public function newPivotQuery()
    {
        parent::newPivotQuery();
    }
}
```
and it gives this error:


-----------

this is the method that get's the error:

```php
        $collection = $user->collection()->updateExistingPivot($animeId, [
            'episodes' => $request->episodes,
            'status' => $request->status
        ]);
```

and the relation:
```php
    /**
     * @var array Relations
     */
    public $belongsToMany = [
        'collection' => [
            Anime::class, 
            'table' => 'anime_queue',
            'key' => 'user_id',
            'otherKey' => 'anime_id',
            'pivot' => ['status', 'episodes', 'score', 'anilist_id'],
            'timestamps' => true
        ],
        'watchlist' => [
            Episode::class,
            'table' => 'anime_episodes_watchlist',
            'key' => 'user_id',
            'otherKey' => 'episode_id',
            'pivot' => ['progress'],
            'timestamps' => true
        ]
    ];
```

anything utilizing a pivot would get affected.
Whether im using updateExistingPivot or syncWithoutDetaching, if i touch the pivot it will error out.

**Comment by mjauvin** [comment]
@Teranode in the code you modified, you need to RETURN the query or the parent's method response...

**Comment by mjauvin** [comment]
What is the exact error when using this PR as is?

**Comment by Denoder** [comment]
> @Teranode in the code you modified, you need to RETURN the query or the parent's method response...

you're right, that fixed it.


> What is the exact error when using this PR as is?

**Comment by mjauvin** [comment]
I don't understand, do you have a `status` field in the pivot table AND in the related table?

**Comment by Denoder** [comment]
@mjauvin yes, and that could easily be solved by just specifying the table name within `updateExistingPivot` however this error did not occur at all before, it's also saying that the update field is ambiguous because both the tables have an updated_at field

**Comment by mjauvin** [comment]
Yes, we're going to have to make more changes, this is now joining two tables which was not the case before.

**Comment by mjauvin** [comment]
@LukeTowers ~how can we select specific fields on the joined table (not the pivot) for the query?~

-- never mind

**Comment by mjauvin** [comment]
@Teranode could you try adding a select to the newPivotQuery() to select only the fields of the pivot table to restore previous behavior? 

Something like this:
```
    public function newPivotQuery()
    {   
        $query = parent::newPivotQuery();

        // add relation's conditions and scopes to the query
        $this->addDefinedConstraintsToQuery($query);

        $related = $this->getRelated();

        return $query
            ->join($related->getTable(), $related->getQualifiedKeyName(), '=', $this->getOtherKey())
            ->select($this->getTable().'.*');
    }
```

**Comment by Denoder** [comment]
the same thing happens unfortunately :(

**Comment by mjauvin** [comment]
@Teranode I tried to reproduce this and I failed...

Are you sure you are using the 1.1.x branch?

**Comment by mjauvin** [comment]
@Teranode do you happen to use cast/json fields in your model? Can you how the full model class?

**Comment by Denoder** [comment]
here: https://gist.github.com/Teranode/36d2c4328d1704fdfe2ab3d5dbfc3d50

**Comment by mjauvin** [comment]
@Teranode can you try different things to pinpoint why you are getting the error and I am not?

Can you temporarily remove the TranslatableModel behavior just to make sure this is not causing the problem?

Thanks for your help with this man!

**Comment by mjauvin** [comment]
I added a pivot data test that calls `updateExistingPivot()` to try to reproduce your issue. Can you take a look at the test and see what's different with your usage?

**Comment by Denoder** [comment]
Would this work?

```
    /**
     * Create a new query builder for the pivot table.
     *
     * This is an extension of Laravel's `newPivotQuery` method that allows `belongsToMany` and `morphToMany` relations
     * to have conditions.
     *
     * @return \Illuminate\Database\Query\Builder
     */
    public function newPivotQuery()
    {
        $query = parent::newPivotQuery();

        // add relation's conditions and scopes to the query
        $this->addDefinedConstraintsToQuery($query);

        $related = $this->getRelated();

        return $query;
    }
```

adding the join breaks it, even just leaving the select works, but when you add the join it breaks.

**Comment by Denoder** [comment]
also here's another gist of a section using the updateExistingPivot/syncWithoutDetaching:
https://gist.github.com/Teranode/b7fd284bbddbbf987e822085329d5095

any instance of that being used will just not work, and i have several files that uses updateExistingPivot.

**Comment by mjauvin** [comment]
@Teranode any way to create a plugin on github with your models and controller that would help me to diagnose this? That'd be awesome!

**Comment by Denoder** [comment]
I don't think I can do that, this seems to only be a problem with me I suppose. I don't know why, so I guess ill just put this in my bridge. No one else seems to have reported an issue.

**Comment by LukeTowers** [comment]
@Teranode it would really help if you could, if it's a problem with you then it's quite possible it will affect others too. You seem to be the only one reporting it at the moment because you actually use the latest code.

**Comment by mjauvin** [comment]
@LukeTowers I added the tests but still cannot reproduce this myself.

**Comment by mjauvin** [comment]
@cjkpl if you want to test this, I've merged the change I showed you earlier.

**Comment by Denoder** [comment]
I'm still recieving the same error if i keep
```
    ->join($related->getTable(), $related->getQualifiedKeyName(), '=', $this->getOtherKey())
    ->select($this->getTable().'.*')
```

**Comment by mjauvin** [comment]
@Teranode please provide us with a plugin to test this, or a PR to the October Test plugin so that we can replicate the issue.

**Pull request merged**
