### PR TITLE
Code to work with the pull request 'Add support for more than one nes…

### PR DESCRIPTION
**Pull request by SiyuQian**
…ted folder in the CMS file browser' #3441

Support max two levels nested folders in the Partial folder

Please see more details in https://github.com/octobercms/october/pull/3441

Cheers,
Siyu Qian

### CODE REVIEW

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Comment by bennothommo** [comment]
@LukeTowers just to note, this circles back to our discussion on the `select` method from `FileDatasource`, where it only allows one level of subdirectories. If that was allowed extra levels, I believe this issue would be resolved, although, I assume @daftspunk had a reasoning for limiting it to one level, whether it's a technical or UI reasoning.

**Comment by LukeTowers** [comment]
@bennothommo yep. I believe the reason was for the UI, if we can implement a refactor the UI that supports arbitrary folder depth cleanly (I think the asset list already does this, but changes would need to be ported over) then we can remove the limit.

**Comment by bennothommo** [comment]
@LukeTowers cool, I'll take a look at this in 467.

**Comment by bennothommo** [comment]
Oops, this is a PR, not an issue. I'll leave myself assigned as a reminder.

**Pull request closed without merging**
