### PR TITLE
Cleanup auth manager

### PR DESCRIPTION
**Pull request by jacobdekeizer**
As discussed with @daftspunk, I would make a pr for changes to the auth manager.

- Fix issues with auth manager so it follows the illuminate contracts.
- Fix autocompletion issues

### CODE REVIEW

**Comment by bennothommo** [comment]
@jacobdekeizer Would the try/catch blocks you have used to catch `AuthException` instances result in different functionality, as those exceptions were passed through before?

**Comment by jacobdekeizer** [comment]
@bennothommo yes it would. But the auth manager didn't follow the laravel contracts. If someone uses a package that is using these contracts it would not work, because this implementation would throw exceptions, where the contract says it only returns true or false. That could lead to unfixable errors.

**Comment by bennothommo** [comment]
@jacobdekeizer I understand, however, given that the Auth in October has operated so long in a specific fashion, it is incredibly likely that people have based their own custom auth implementations around the way our auth functions right now. I know that several people use our Auth for API-driven developments, and I cannot discount that they may be relying on `AuthException` instances being thrown.

I'll have a chat with the team and work out if this is an acceptable BC break or not.

**Comment by jacobdekeizer** [comment]
I think this is the right time to make such a change, we all have to check our code with the laravel 6 upgrade.

**Comment by LukeTowers** [comment]
The L6 upgrade is not an excuse to put in breaking changes. As is right now the October auth system requires some level of custom work per project to make work with most Laravel auth packages (although a lot less than it used to) so I see no benefit of introducing the breaking change of no longer passing along exceptions for the sake of "some packages that might not expect an exception to be thrown".

**Pull request closed without merging**
