### PR TITLE
Correct fixture target image for ResizerTest

### PR DESCRIPTION
**Pull request by petehalverson**
[ResizerTest::testResizeAutoExifRotated30x30() ](https://github.com/octobercms/library/blob/master/tests/Database/Attach/ResizerTest.php#L310-L322)

When the resize method is called with the auto mode and 30x30 dimensions the saved image should have the EXIF rotation applied.

> Note. The source appears landscape when using a viewer that doesn't honor the EXIF data containing the rotation.

Nice work @Notuom!

### CODE REVIEW

**Comment by petehalverson** [comment]
Huh. Something's amiss here @LukeTowers. I'll dig into it further...

**Comment by petehalverson** [comment]
[Source image exif data](http://metapicz.com/#landing?imgsrc=https%3A%2F%2Fraw.githubusercontent.com%2Foctobercms%2Flibrary%2F4a7fd57f53257d1d07974ea44e8808a2c6bf8448%2Ftests%2Ffixtures%2Fresizer%2Fsource%2Flandscape_rotated.jpg)

**Comment by petehalverson** [comment]
Sorry, my bad. EXIF support wasn't enabled within our Docker image. I guess I misunderstood the purpose of this test.

**Comment by LukeTowers** [comment]
No problem @petehalverson, always appreciate the checkin!

**Pull request closed without merging**
