### PR TITLE
Change asset compiling

### PR DESCRIPTION
**Pull request by christianWilling**
https://github.com/octobercms/library/pull/220

this should say everything

### CODE REVIEW

**Comment by LukeTowers** [comment]
Did you remove the leafo requirement after switching the less processing back to [Less_Parser](https://github.com/oyejorge/less.php)?

**Comment by christianWilling** [comment]
no i don't

**Comment by christianWilling** [comment]
now it is fixed

**Comment by LukeTowers** [comment]
I'm not certain where the LessphpFilter is defined, you reference it but I don't know where it is. Also I've replaced my Parse\Assetic\LessCompiler.php file with its content from your latest commit but it doesn't seem to actually be doing it's job, which is to implement the native caching functions of Less_Parse to provide recompilation when imported less files are modified, instead of having to save the main less file to trigger recompilation.

I'm not entirely certain of what exactly this pull request does, do you mind explaining it a bit more?

**Comment by christianWilling** [comment]
https://github.com/octobercms/october/pull/2180
Here you can see what this should do an of course you can't see any difference without changing the asset combiner class.

And the original less paser uses the `Less_Parser`

**Comment by LukeTowers** [comment]
Thanks, I didn't realize there was a pull request in the october repo that this would utilize.

I've modified my local System\Classes\CombineAssets to add to the prepareCominer() method with the code from your other pull request
```php
$cachedFiles = [];
foreach ($files as $file) {
    $cachedFiles[] = new AssetCache($file, $cache);
}

$cachedCollection = new AssetCollection($cachedFiles, [], $filesSalt);
$cachedCollection->setTargetPath($this->getTargetPath($rewritePath));
```

and modified my local October\Rain\Parse\Assetic\LessCompiler as specified in this PR

```php
<?php namespace October\Rain\Parse\Assetic;

use Event;
use Less_Parser;
use Assetic\Asset\AssetInterface;
use Assetic\Factory\AssetFactory;
use Assetic\Filter\LessphpFilter;
use Assetic\Filter\HashableInterface;
use Assetic\Filter\FilterInterface;
use Cms\Classes\Theme;

/**
 * Less.php Compiler Filter
 * Class used to compiled stylesheet less files, not using leafo!
 *
 * @package october/parse
 * @author Alexey Bobkov, Samuel Georges
 */
class LessCompiler implements FilterInterface,HashableInterface
{
    protected $currentFiles = [];
    protected $presets = [];

    public function __construct(){
        Event::listen('cms.combiner.beforePrepare', function($compiler, $assets) {
            foreach ($assets as $asset) {
                if(pathinfo($asset)['extension'] == 'less'){
                    $this->currentFiles[] = $asset;
                }
            }
        });
    }

    public function setPresets(array $presets)
    {
        $this->presets = $presets;
    }

    public function filterLoad(AssetInterface $asset)
    {
        $parser = new Less_Parser();

        // CSS Rewriter will take care of this
        $parser->SetOption('relativeUrls', false);

        $parser->parseFile($asset->getSourceRoot() . '/' . $asset->getSourcePath());

        // Set the LESS variables after parsing to override them
        $parser->ModifyVars($this->presets);

        $asset->setContent($parser->getCss());
    }

    public function filterDump(AssetInterface $asset)
    {
    }

    /**
     * Generates a hash for the object
     *
     * @return string Object hash
     */
    public function hash(){
        $themePath = themes_path(Theme::getActiveTheme()->getDirName());
        $factory = new AssetFactory($themePath);

        $allFiles = [];

        foreach ($this->currentFiles as $file) {
           $children = $this->getChildren($factory, file_get_contents($themePath.'/'.$file), $themePath.'/'.dirname($file));
           foreach ($children as $child) {
               $allFiles[] = $child;
           }
        }

        $modifieds = [];

        foreach ($allFiles as $file) {
           $modifieds[] = $file->getLastModified();
        }

        return md5(implode('|', $modifieds));
    }

    //load children recusive
    public function getChildren(AssetFactory $factory, $content, $loadPath = null){
        $children = LessphpFilter::getChildren($factory, $content, $loadPath);

        foreach ($children as $child) {
            $childContent = file_get_contents($child->getSourceRoot().'/'.$child->getSourcePath());
            $children= array_merge($children, LessphpFilter::getChildren($factory, $childContent, $loadPath.'/'.dirname($child->getSourcePath())));
        }

        return $children;
    }
}
```

However the combined assets are now passed to the browser with the mime type text/html and no contents. Is there something else I'm missing?

**Comment by christianWilling** [comment]
No in my case this worked but anyway I don't mods the real render function of the filter I only added the hash and the get children functions to change the caching for included files. So can you compile scss files if you add the scss filter or is there something in your error log?

**Comment by LukeTowers** [comment]
I haven't tried compiling scss files yet, my project relies on less files unfortunately so I was attempting to get this to work. Unfortunately I don't see anything in my logs either as to what exactly is failing, I'll have to take a deeper look into this to see if I can figure out what's going wrong. 

In theory though, as long as I've modified LessCompiler and CombineAssets with your code the new Less caching that supports imported files should work perfectly? Or is there another step that I'm missing somewhere?

**Comment by christianWilling** [comment]
Now if every file is chached for its own (the changes in the asset Compiler) and the filter has an Hash  function and the interface hash able it should work. I'm currently not at an PC so sry if I ask but are you shure that you copied the hole prepareCombiner function ?

**Comment by LukeTowers** [comment]
Yep, this is what my entire prepareCombiner function looks like:
```
/**
     * Returns the combined contents from a prepared cache identifier.
     * @return string Combined file contents.
     */
    protected function prepareCombiner(array $assets, $rewritePath = null)
    {
        /*
         * Extensibility
         */
        Event::fire('cms.combiner.beforePrepare', [$this, $assets]);

        $files = [];
        $filesSalt = null;
        foreach ($assets as $asset) {
            $filters = $this->getFilters(File::extension($asset)) ?: [];
            $path = File::symbolizePath($asset, null) ?: $this->localPath . $asset;
            $files[] = new FileAsset($path, $filters, public_path());
            $filesSalt .= $this->localPath . $asset;
        }
        $filesSalt = md5($filesSalt);

        $collection = new AssetCollection($files, [], $filesSalt);
        $collection->setTargetPath($this->getTargetPath($rewritePath));

        if ($this->storagePath === null) {
            return $collection;
        }

        if (!File::isDirectory($this->storagePath)) {
            File::makeDirectory($this->storagePath);
        }

        $cache = new FilesystemCache($this->storagePath);
        
        $cachedFiles = [];
        foreach ($files as $file) {
            $cachedFiles[] = new AssetCache($file, $cache);
        }

        $cachedCollection = new AssetCollection($cachedFiles, [], $filesSalt);
        $cachedCollection->setTargetPath($this->getTargetPath($rewritePath));
        
        return $cachedCollection;
    }
```

And my entire LessCompiler class:

```
<?php namespace October\Rain\Parse\Assetic;

use Event;
use Less_Parser;
use Assetic\Asset\AssetInterface;
use Assetic\Factory\AssetFactory;
use Assetic\Filter\LessphpFilter;
use Assetic\Filter\HashableInterface;
use Assetic\Filter\FilterInterface;
use Cms\Classes\Theme;

/**
 * Less.php Compiler Filter
 * Class used to compiled stylesheet less files, not using leafo!
 *
 * @package october/parse
 * @author Alexey Bobkov, Samuel Georges
 */
class LessCompiler implements FilterInterface,HashableInterface
{
    protected $currentFiles = [];
    protected $presets = [];

    public function __construct(){
        Event::listen('cms.combiner.beforePrepare', function($compiler, $assets) {
            foreach ($assets as $asset) {
                if(pathinfo($asset)['extension'] == 'less'){
                    $this->currentFiles[] = $asset;
                }
            }
        });
    }

    public function setPresets(array $presets)
    {
        $this->presets = $presets;
    }

    public function filterLoad(AssetInterface $asset)
    {
        $parser = new Less_Parser();

        // CSS Rewriter will take care of this
        $parser->SetOption('relativeUrls', false);

        $parser->parseFile($asset->getSourceRoot() . '/' . $asset->getSourcePath());

        // Set the LESS variables after parsing to override them
        $parser->ModifyVars($this->presets);

        $asset->setContent($parser->getCss());
    }

    public function filterDump(AssetInterface $asset)
    {
    }

    /**
     * Generates a hash for the object
     *
     * @return string Object hash
     */
    public function hash(){
        $themePath = themes_path(Theme::getActiveTheme()->getDirName());
        $factory = new AssetFactory($themePath);

        $allFiles = [];

        foreach ($this->currentFiles as $file) {
           $children = $this->getChildren($factory, file_get_contents($themePath.'/'.$file), $themePath.'/'.dirname($file));
           foreach ($children as $child) {
               $allFiles[] = $child;
           }
        }

        $modifieds = [];

        foreach ($allFiles as $file) {
           $modifieds[] = $file->getLastModified();
        }

        return md5(implode('|', $modifieds));
    }

    //load children recusive
    public function getChildren(AssetFactory $factory, $content, $loadPath = null){
        $children = LessphpFilter::getChildren($factory, $content, $loadPath);

        foreach ($children as $child) {
            $childContent = file_get_contents($child->getSourceRoot().'/'.$child->getSourcePath());
            $children= array_merge($children, LessphpFilter::getChildren($factory, $childContent, $loadPath.'/'.dirname($child->getSourcePath())));
        }

        return $children;
    }
}
```

**Comment by christianWilling** [comment]
Can you mail me an zip with your less file or with your project I'll look at this error at the weekend.

**Comment by christianWilling** [comment]
Can you mail me an zip with your less file or with your project I'll look at this error at the weekend.

**Comment by christianWilling** [comment]
@daftspunk now the functionality should be complete.

with the other pull request https://github.com/octobercms/october/pull/2180

**Comment by daftspunk** [comment]
Thanks @christianWilling! Will take a look soon.

Also #2180 is submitted to the wrong branch, should be `develop`

**Comment by christianWilling** [comment]
i added new PR https://github.com/octobercms/october/pull/2248 to the correct branch

**Comment by LukeTowers** [comment]
I've updated my October dependencies to the latest, and now get the error `/* Non-static method Assetic\Filter\LessphpFilter::getChildren() should not be called statically */` displayed in my combined CSS file that gets served to the browser.

**Comment by LukeTowers** [comment]
Changing the `getChildren` method in `LessCompiler` to use `(new LessphpFilter)->getChildren()` instead of `LessphpFilter::getChildren()` works perfectly now. I also put a proper docblock in there as well:
```php
/**
 * Load children recursively
 * 
 * @param AssetFactory $factory
 * @param $content
 * @param $loadPath
 * @return array $children
 */
public function getChildren(AssetFactory $factory, $content, $loadPath = null){
    $children = (new LessphpFilter)->getChildren($factory, $content, $loadPath);

    foreach ($children as $child) {
        $childContent = file_get_contents($child->getSourceRoot().'/'.$child->getSourcePath());
        $children= array_merge($children, (new LessphpFilter)->getChildren($factory, $childContent, $loadPath.'/'.dirname($child->getSourcePath())));
    }

    return $children;
}
```

**Comment by christianWilling** [comment]
i have added your changes.
but i cant understand how this worked in my test case ....

**Comment by LukeTowers** [comment]
What sort of an environment are you running as far as PHP version and settings go? I'm using the Laravel Homestead box as my environment if that helps

**Comment by daftspunk** [comment]
Is there an outstanding problem here?

**Comment by christianWilling** [comment]
i think no. And if i had understand him right @LukeTowers has all my changes und uses them and found some error in the less filter and i fixed it with https://github.com/octobercms/library/pull/225/commits/2c046915f7d9c2235007be20f1545e8308ac9974 from his workaround so everything should runs fine now on my testsystems.

and @LukeTowers 
i have an 
mac with apache and php7 on work 
an win10 with nginx and php7 and php5.6
and an debain 8 with nginx on my webserver

**Comment by LukeTowers** [comment]
@daftspunk nope, it all works good on my end now. @christianWilling what version of Assetic are you using? If you check your local copy of LessphpFilter are those methods static?

**Comment by amdad** [comment]
@daftspunk What exactly enableAssetDeepHashing  do? 

@christianWilling With this update (build 353) your plugin/willing-scss is redundant? All features are include? What about `|theme` filter for relative paths?

**Comment by daftspunk** [comment]
/*
    |--------------------------------------------------------------------------
    | Check import timestamps when combining assets
    |--------------------------------------------------------------------------
    |
    | If deep hashing is enabled, the combiner cache will be reset when a change
    | is detected on imported files, in addition to those referenced directly.
    | This will cause slower page performance. If set to null, assets are
    | minified, when debug mode (app.debug) is disabled.
    |
    */
    'enableAssetDeepHashing' => false,

**Comment by amdad** [comment]
I forgot about those comments in config. Thanks!

**Comment by christianWilling** [comment]
@amdad all features  are included.

@daftspunk whats is now the right way to close my plugin?

**Comment by amdad** [comment]
@christianWilling works brilliant! Thanks!

**Comment by daftspunk** [comment]
@christianWilling Put a note on it that it is no longer maintained since the feature exists in core. If it is listed on the OctoberCMS website, there is an option to hide it as an author.

**Pull request merged**
