### PR TITLE
Support for handling proxies

### PR DESCRIPTION
**Pull request by JoelESvensson**
See: https://github.com/octobercms/october/pull/2250

### CODE REVIEW

**Comment by daftspunk** [comment]
Looks like a nice elegant solution. This should really be handled as a plugin to minimise the bloat on the platform. What do you think?

**Comment by JoelESvensson** [comment]
I definitely agree. The problem is that I don't know how to programatically push the middleware to the global stack with a plugin.

**Comment by daftspunk** [comment]
Take a look here for details on how to do it: https://github.com/octobercms/docs/pull/167

**Comment by JoelESvensson** [comment]
Ah, thanks! Is `CmsController` where you would put global middleware?

**Comment by daftspunk** [comment]
Prepending or appending to the Http contract (see the PR changes) would make it truly global. Attaching to `CmsController` or `BackendController` would affect that instance only.

**Comment by JoelESvensson** [comment]
Closing this in favor of the plugin
https://github.com/JoelESvensson/october-trusted-proxy

**Comment by JoelESvensson** [comment]
Unfortunately the plugin solution doesn't work on paths where plugins are disabled. More specifically the ones here: https://github.com/octobercms/october/blob/master/modules/system/ServiceProvider.php#L115

How do you think I should solve this @daftspunk?

**Comment by daftspunk** [comment]
@JoelESvensson, this is an artificial wall to stop plugins from breaking critical functionality. Set this property to `true` in your plugin information class to overcome it.

    /**
     * @var boolean Determine if this plugin should have elevated privileges.
     */
    public $elevated = true;

**Pull request closed without merging**
