### PR TITLE
Implement DataFeed pagination

### PR DESCRIPTION
**Pull request by adsa95**
DataFeed pagination is listed in the documentation but not implemented (Issue octobercms/october#2415), this pull request fix that. While I worked on it I also discovered that the DataFeed->count() function did not work when the query had bindings, so I fixed that as well.

The implementation is based on the implementation from the Eloquent Builder.

Please note that I have only tested this for on a site that I'm working on and some more tests might be necessary.

### CODE REVIEW

**Comment by adsa95** [comment]
Apparently I was a bit quick on this one, the next/previous links are currently not working correctly (always using root path).

**Comment by adsa95** [comment]
Fixed!

**Comment by LukeTowers** [comment]
This pull request has been made to the wrong branch. Please review [the contributing guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#pull-requests) as all PRs need to be made to the develop branch.

I'll fix it for you this time, but please ensure you make any future PRs to the develop branch, not the master branch.

**Comment by LukeTowers** [comment]
Please rebase to develop branch

**Comment by LukeTowers** [comment]
Thanks for your work on this btw @adsa95, I can't wait to review it!

**Comment by adsa95** [comment]
Sorry about the branch, I've rebased it now @LukeTowers

**Comment by romanseki** [comment]
Hello, I tried implement this commit in my project but I got an error 
Type error: Argument 1 passed to Illuminate\Database\Query\Builder::mergeBindings() must be an instance of Illuminate\Database\Query\Builder, instance of October\Rain\Database\Builder given, called in /Applications/MAMP/htdocs/liekysrozumom.sk/vendor/october/rain/src/Database/DataFeed.php on line 98
any solutions?

**Comment by dimensi** [comment]
It's been three years since the pull request was made, is there any good news?
@adsa95, @LukeTowers

**Comment by LukeTowers** [comment]
@dimensi It's been a year and a half, and no, I haven't tested it at all. If you can test it and verify that it works for all situations that you can think of, then we could look at merging it. 

What are you talking about in regards to `extract` `compact`?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Pull request closed without merging**
