### PR TITLE
Add scssphp/scssphp

### PR DESCRIPTION
**Pull request by greatislander**
[scssphp has moved](https://github.com/scssphp/scssphp/issues/4). This PR updates the composer dependency.

### CODE REVIEW

**Comment by LukeTowers** [comment]
@greatislander looking into this more I don't think we actually use that dependency directly anywhere in our own code, we just pull in Assetic and assetic uses it.

**Comment by bennothommo** [comment]
@LukeTowers Looks like Assetic hasn't had a [commit](https://github.com/kriswallsmith/assetic/commits/master) since November 2016, so it's unlikely they'll change it.

**Comment by LukeTowers** [comment]
It's unlikely that we'll change it either, I don't even think we use it directly, I think we can just remove it from our composer.json altogether

**Comment by LukeTowers** [comment]
blocked until assetic updates their copy

**Comment by bennothommo** [comment]
This is going to be resolved by the L6 upgrade, when we switch over to using the new [Assetic fork](https://github.com/assetic-php/assetic).

**Pull request closed without merging**
