### PR TITLE
Add data-request-validate to the controller scaffolding

### PR DESCRIPTION
**Pull request by LukeTowers**
Related: https://github.com/octobercms/october/pull/5088

### CODE REVIEW

**Comment by bennothommo** [comment]
@LukeTowers I'd probably suggest leaving this out of controller scaffolding and making it opt-in.

**Comment by LukeTowers** [comment]
@bennothommo why do you say that? In my mind having it run on every "submit" AJAX request is desirable and a better experience.

**Comment by bennothommo** [comment]
@LukeTowers My opinion is that browser based validation is too intrusive, in that it steals focus. It also sometimes is too unclear on the issue at hand (when dealing with regex or number validation for example). I also imagine that people might get frustrated when they finally resolve all browser validation issues only to get another validation error from within October, for things that the browser validation cannot check (like duplicate slugs).

**Comment by LukeTowers** [comment]
@bennothommo I see what you're saying. I would be more inclined to remove it from the scaffolding if the inline form validation feature was complete and enabled by default, but as it stands right now I think the browser-based client validation is more useful than harmful for the bulk of users given that the only other validation performed is one error at a time server side validation, which in my opinion is a worse user experience than browser-based.

**Pull request merged**
