### PR TITLE
Reformat code & cleanup

### PR DESCRIPTION
**Pull request by Samuell1**
Hey,

i run repository trough light reformatter and cleanup to be more consistent with all changes from multiple people in years.

### CODE REVIEW

**Comment by daftspunk** [comment]
Hi @Samuell1 

This is a lot to review. Did you do this by hand?

**Comment by Samuell1** [comment]
@daftspunk it was done trough phpstorm reformatter

**Comment by daftspunk** [comment]
Unfortunately, this touches too many files and creates problems with merging between branches.

**Comment by Samuell1** [comment]
I can later do it on most recent branch and separately per folder

**Pull request closed without merging**
