### PR TITLE
Alternative fix for october#5499

### PR DESCRIPTION
**Pull request by bennothommo**
Applies the fix suggested by @LukeTowers here: https://github.com/octobercms/library/pull/562#discussion_r580083985

Also adjusts the unit tests to try conditions and scopes in the relation config.

Replaces https://github.com/octobercms/library/pull/562

### CODE REVIEW

**Comment by bennothommo** [comment]
@Teranode could you try this fix instead with your setup (just the changes for [`DefinedConstraints`](https://github.com/octobercms/library/pull/563/files#diff-56f77bab4b0aa050a15e11466ccccbe82ce391f7adeed778ddc5c66c41152127)) and let me know if that has any better luck?

**Comment by mjauvin** [comment]
@bennothommo I confirm this way of calling the scope fixes the problem either using conditions or scope for the relation definition.

I tried Luke's second suggested method and didn't try the first one.

Nice work guys!

**Comment by Denoder** [comment]
@bennothommo Still the same thing

**Comment by LukeTowers** [comment]
@Teranode were you able to provide reproduction instructions with the test plugin? That would help us out a lot with solving your issue.

**Comment by bennothommo** [comment]
@LukeTowers As far as I can tell, @Teranode's scenario is that they're using a field name that is ambiguous in the conditions. Is this correct, @Teranode?

I would say a potential fix is to prefix the field with the relation name which would remove the ambiguity, but I haven't tried that out yet.

**Comment by Denoder** [comment]
> @LukeTowers As far as I can tell, @Teranode's scenario is that they're using a field name that is ambiguous in the conditions. Is this correct, @Teranode?
> 
> I would say a potential fix is to prefix the field with the relation name which would remove the ambiguity, but I haven't tried that out yet.

yes and no, yes in the sense that the `status` field is ambiguous and i could change it. No in the sense that when I do change it. the `updated_at` field gets called ambiguous because the pivot method is ambiguously trying to update the `status` and `updated_at` field which both tables have.

**Comment by bennothommo** [comment]
@Teranode and this is happening when using `updateExistingPivot`?

**Comment by Denoder** [comment]
> @Teranode and this is happening when using `updateExistingPivot`?

yes and also syncWithoutDetaching

**Comment by bennothommo** [comment]
Cool - I'll try add it to the tests.

**Pull request closed without merging**
