### PR TITLE
Fix dependencies

### PR DESCRIPTION
**Pull request by SeriousKen**
Currently can't do composer install as there are dependency conflicts.

Updated swiftmailer to 6.0
Updated symfony config to 3.1

### CODE REVIEW

**Comment by LukeTowers** [comment]
@SeriousKen what's the conflicting package with symfony/config?

**Comment by SeriousKen** [comment]
This is what I get just switching to Swiftmailer 6.0, upgrading symfony/config solves this.

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install illuminate/routing 5.5.x-dev
    - Conclusion: don't install illuminate/routing v5.5.28
    - Conclusion: don't install illuminate/routing v5.5.17
    - Conclusion: don't install illuminate/routing v5.5.16
    - Conclusion: don't install illuminate/routing v5.5.2
    - Conclusion: don't install symfony/config 2.7.x-dev
    - Conclusion: don't install symfony/config v2.7.40
    - Conclusion: don't install symfony/config v2.7.39
    - Conclusion: don't install symfony/config v2.7.38
    - Conclusion: don't install symfony/config v2.7.37
    - Conclusion: don't install symfony/config v2.7.36
    - Conclusion: don't install symfony/config v2.7.35
    - Conclusion: don't install symfony/config v2.7.34
    - Conclusion: don't install symfony/config v2.7.33
    - Conclusion: don't install symfony/config v2.7.32
    - Conclusion: don't install symfony/config v2.7.31
    - Conclusion: don't install symfony/config v2.7.30
    - Conclusion: don't install symfony/config v2.7.29
    - Conclusion: don't install symfony/config v2.7.28
    - Conclusion: don't install symfony/config v2.7.27
    - Conclusion: don't install symfony/config v2.7.26
    - Conclusion: don't install symfony/config v2.7.25
    - Conclusion: don't install symfony/config v2.7.24
    - Conclusion: don't install symfony/config v2.7.23
    - Conclusion: don't install symfony/config v2.7.22
    - Conclusion: don't install symfony/config v2.7.21
    - Conclusion: don't install symfony/config v2.7.20
    - Conclusion: don't install symfony/config v2.7.19
    - Conclusion: don't install symfony/config v2.7.18
    - Conclusion: don't install symfony/config v2.7.17
    - Conclusion: don't install symfony/config v2.7.16
    - Conclusion: don't install symfony/config v2.7.15
    - Conclusion: don't install symfony/config v2.7.14
    - Conclusion: don't install symfony/config v2.7.13
    - Conclusion: don't install symfony/config v2.7.12
    - Conclusion: don't install symfony/config v2.7.11
    - Conclusion: don't install symfony/config v2.7.10
    - Conclusion: don't install symfony/config v2.7.9
    - Conclusion: don't install symfony/config v2.7.8
    - Conclusion: don't install symfony/config v2.7.7
    - Conclusion: don't install symfony/config v2.7.6
    - Conclusion: don't install symfony/config v2.7.5
    - Conclusion: don't install symfony/config v2.7.4
    - Conclusion: don't install symfony/config v2.7.3
    - Conclusion: don't install symfony/config v2.7.2
    - Conclusion: don't install symfony/config v2.7.1
    - Conclusion: don't install symfony/config v2.7.0
    - Installation request for illuminate/routing 5.5.* -> satisfiable by illuminate/routing[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - Conclusion: don't install symfony/config v2.7.0-BETA2
    - illuminate/routing v5.5.0 requires symfony/routing ~3.3 -> satisfiable by symfony/routing[3.3.x-dev, 3.4.x-dev, v3.3.0, v3.3.0-BETA1, v3.3.0-RC1, v3.3.1,
v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.0-BETA1, v3.4.0-BETA2, v3.4.0-BETA3, v3.4.0-BETA4, v3.4.0-RC1, v3.4.0-RC2, v3.4.1, v3.4.2, v3.4.3].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[3.3.x-dev].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[3.4.x-dev].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.3.0].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.3.0-BETA1].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.3.0-RC1].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.3.1].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.3.10].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.3.11].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.3.12].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.3.13].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.3.14].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.3.15].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.3.2].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.3.3].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.3.4].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.3.5].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.3.6].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.3.7].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.3.8].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.3.9].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.4.0].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.4.0-BETA1].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.4.0-BETA2].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.4.0-BETA3].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.4.0-BETA4].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.4.0-RC1].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.4.0-RC2].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.4.1].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.4.2].
    - symfony/config v2.7.0-BETA1 conflicts with symfony/routing[v3.4.3].
    - Installation request for symfony/config 2.7.* -> satisfiable by symfony/config[2.7.x-dev, v2.7.0, v2.7.0-BETA1, v2.7.0-BETA2, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.30, v2.7.31, v2.7.32, v2.7.33, v2.7.34, v2.7.35, v2.7.36, v2.7.37, v2.7.38, v2.7.39, v2.7.4, v2.7.40, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9].

**Comment by SeriousKen** [comment]
Just tested and upgrading symfony/config to 2.8.* also resolves this. Would this be a better dependency?

**Comment by LukeTowers** [comment]
Could you look into any breaking changes with the latest version of symfony/config vs the current version used in October and see if they will affect us? If they won't, then I don't see an issue going with the latest version

**Comment by SeriousKen** [comment]
The only changes in symfony/config seem to be:

    removed ReferenceDumper class
    removed the ResourceInterface::isFresh() method
    removed BCResourceInterfaceChecker class
    removed ResourceInterface::getResource() method

These don't appear to be used in October as far as I can tell.

**Comment by LukeTowers** [comment]
@SeriousKen do all the tests still pass with these new dependencies?

**Comment by SeriousKen** [comment]
@LukeTowers yes, all tests pass

**Comment by buuug7** [comment]
@LukeTowers need update the dependencies.
```
  Problem 1
    - Installation request for swiftmailer/swiftmailer ~5.1 -> satisfiable by swiftmailer/swiftmailer[5.x-dev, v5.1.0
, v5.2.0, v5.2.1, v5.2.2, v5.3.0, v5.3.1, v5.4.0, v5.4.1, v5.4.2, v5.4.3, v5.4.4, v5.4.5, v5.4.6, v5.4.7, v5.4.8].
    - illuminate/mail 5.5.x-dev requires swiftmailer/swiftmailer ~6.0 -> satisfiable by swiftmailer/swiftmailer[6.0.x
-dev].
    - illuminate/mail v5.5.0 requires swiftmailer/swiftmailer ~6.0 -> satisfiable by swiftmailer/swiftmailer[6.0.x-de
v].
    - illuminate/mail v5.5.16 requires swiftmailer/swiftmailer ~6.0 -> satisfiable by swiftmailer/swiftmailer[6.0.x-d
ev].
    - illuminate/mail v5.5.17 requires swiftmailer/swiftmailer ~6.0 -> satisfiable by swiftmailer/swiftmailer[6.0.x-d
ev].
    - illuminate/mail v5.5.2 requires swiftmailer/swiftmailer ~6.0 -> satisfiable by swiftmailer/swiftmailer[6.0.x-de
v].
    - illuminate/mail v5.5.28 requires swiftmailer/swiftmailer ~6.0 -> satisfiable by swiftmailer/swiftmailer[6.0.x-d
ev].
    - Conclusion: don't install swiftmailer/swiftmailer 6.0.x-dev
    - Installation request for illuminate/mail 5.5.* -> satisfiable by illuminate/mail[5.5.x-dev, v5.5.0, v5.5.16, v5
.5.17, v5.5.2, v5.5.28].

vagrant@homestead:~/Code/Library$

```

**Comment by LukeTowers** [comment]
@SeriousKen @buuug7 I just had a thought, why do we even need to include these packages in this composer.json? As far as I can tell we don't reference them directly so why not just remove them outright and have the dependencies that actually use them load them?

**Comment by jimcottrell** [comment]
@LukeTowers Came across this as well while getting set up to run tests. It does seem like it should just be left to the other dependencies to load those packages. I can confirm that all tests pass after removing entries for `swiftmailer/swiftmailer` and `symfony/config`.

**Comment by LukeTowers** [comment]
Thanks for the confirmation @jimcottrell. @SeriousKen could you just remove those dependencies outright from the composer.json file?

**Comment by SeriousKen** [comment]
I'll have a look

**Pull request merged**
