### PR TITLE
Reverted newlines and zeros

### PR DESCRIPTION
**Pull request by w20k**
Related to:
- https://github.com/octobercms/october/pull/4038
- https://github.com/octobercms/october/issues/4040

### CODE REVIEW

**Comment by LukeTowers** [comment]
This pull request has been made to the wrong branch. Please review [the contributing guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#pull-requests) as all PRs need to be made to the develop branch.

I'll fix it for you this time, but please ensure you make any future PRs to the develop branch, not the master branch.

**Comment by w20k** [comment]
Ops, sorry, @LukeTowers, was in a rush! 👍

**Comment by LukeTowers** [comment]
No problem @w20k 😉

**Comment by ayumihamsaki** [comment]
@w20k @LukeTowers Sorry to ask, are you guys going to re-compile the october.css and other css files that Luke changed 25 days ago in the developer branch?

I got loads of PR's just sitting waiting for that to get sorted and I would like to close them off and then code the rest of my list of PR's.

**Comment by LukeTowers** [comment]
@ayumihamsaki done. You'll have to pull the latest dev branch of the library, minification method needed another change.

**Pull request merged**
