### PR TITLE
Add Sortable Behavior class

### PR DESCRIPTION
**Pull request by mjauvin**
This class allows to extend an existing model and make it sortable by implementing this new Sortable behavior.

This can be done dynamically on an existing model like below:
```
\Author\Plugin\Models\myModel::extend(function ($model) {
   $model->extendClassWith(\October\Rain\Database\Behaviors\Sortable::class);
});
```

You need to make sure there is a "sort_order" field in the database table, or add a migration to add it dynamically.

### CODE REVIEW

**Comment by bennothommo** [comment]
@mjauvin What scenario would we use the behaviour over the already-available trait?

**Comment by mjauvin** [comment]
@bennothommo the trait needs to be added to the class definition... which can't be done when extending a model dynamically.

**Comment by bennothommo** [comment]
@mjauvin you're right, but I mean given that `sort_order` must be a column in the database table already (and thus part of the "model"), I feel it is something that shouldn't be *dynamic* so to speak.

**Comment by LukeTowers** [comment]
@bennothommo I think that it's somewhat reasonable to expect a plugin to be able to add this behavior to another plugin, especially if they're properly prefixing the sort_order column when they change the other plugin's table.

**Comment by mjauvin** [comment]
I'll be doing more tests for this soon.

**Comment by SebastiaanKloos** [comment]
I need this in one of my projects. I am extending the Shopaholic plugin. The products model needs to be sortable. Right now I've added the sort_order column by creating a new migration. I extended the model with dynamic methods based on the Sortable Trait. I can give it a try and test this pr

**Comment by SebastiaanKloos** [comment]
If I'm right (using the Github app on my phone right now) you need to add this to the ReorderController. It checks if the model implements the nested tree or simple tree trait

**Comment by mjauvin** [comment]
No, you need to add this to your model.

**Comment by LukeTowers** [comment]
@mjauvin @SebastiaanKloos is saying that the ReorderController needs to check if the model has implemented this behaviour, right now it checks if it has implemented the Trait instead.

**Comment by SebastiaanKloos** [comment]
> @mjauvin @SebastiaanKloos is saying that the ReorderController needs to check if the model has implemented this behaviour, right now it checks if it has implemented the Trait instead.

Yes you're right!

**Comment by mjauvin** [comment]
Oh, I see, your most definitely right!

I'll add a PR to the ReorderController then...

**Comment by LeMaX10** [comment]
Good day! I created the same thing by styling it into a plugin.
You can use the features and implementation from it if you need it.

https://github.com/LeMaX10/oc-extendedsortable

**Comment by mjauvin** [comment]
@LukeTowers @bennothommo  this is ready for review.

I've tested this and it's working great!

Once reviewed, I can setup an Octodock instance to help you/others test this.

**Comment by mjauvin** [comment]
@SebastiaanKloos could you give this a try, it's working for me now.

You'll also need the related PR (https://github.com/octobercms/october/pull/5268)

Thanks!

**Comment by SebastiaanKloos** [comment]
> @SebastiaanKloos could you give this a try, it's working for me now.
> 
> 
> 
> You'll also need the related PR (https://github.com/octobercms/october/pull/5268)
> 
> 
> 
> Thanks! 

Yes I'll try it with Shopaholic!


Thank you!

**Comment by mjauvin** [comment]
@SebastiaanKloos did you get a chance to test it?

**Comment by mjauvin** [comment]
@LukeTowers you can update the status to "testing needed" and remove the "in progress" as it's complete.

Thanks.

**Comment by SebastiaanKloos** [comment]
@mjauvin I will test it today!

**Comment by SebastiaanKloos** [comment]
@mjauvin  It works in my project. Thanks!

**Comment by mjauvin** [comment]
@LukeTowers It's been tested as working by @SebastiaanKloos and myself.

**Comment by LukeTowers** [comment]
@mjauvin is there a related docs PR?

**Comment by mjauvin** [comment]
Indeed, there is: https://github.com/octobercms/docs/pull/491

:laughing:

**Pull request merged**
