### PR TITLE
Add array views support to MailFake

### PR DESCRIPTION
**Pull request by mjauvin**
Related to https://github.com/octobercms/october/pull/5402

### CODE REVIEW

**Review by bennothommo — APPROVED** [review]

**Comment by bennothommo** [comment]
Blocked by https://github.com/octobercms/october/pull/5402

**Comment by mjauvin** [comment]
@bennothommo this is related but not DEPENDENT on the other PR.

**Comment by mjauvin** [comment]
can this be added to 1.1.2 milestone?

**Comment by bennothommo** [comment]
@mjauvin I'm still going to consider this blocked until the other PR is merged, so we can ensure these tests are still passing with that PR in place.

**Comment by mjauvin** [comment]
ping

**Pull request closed without merging**
