### PR TITLE
Method forceSchema does not exist

### PR DESCRIPTION
**Pull request by lasat**
Fixed Typo

### CODE REVIEW

**Comment by NemoD503** [comment]
+1 to this PR.I have trouble with tests - all test fails with error `BadMethodCallException: Method force Schema does not exist.` when providers register.

**Comment by NemoD503** [comment]
I think, it`s not good, that provider registration depends on config and tests use only **one** variant  of config value (UrlGeneratorPolicy in this case) so test pass only with default config set, but really project fails on start, if user choose "force" UrlGeneratorPolicy.

**Comment by LukeTowers** [comment]
This pull request has been made to the wrong branch. Please review [the contributing guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#pull-requests) as all PRs need to be made to the develop branch.

I'll fix it for you this time, but please ensure you make any future PRs to the develop branch, not the master branch.

**Comment by LukeTowers** [comment]
@NemoD503 does this PR fix the issue for you? @lasat could you please provide a more detailed description of the issue that this PR fixes?

**Comment by NemoD503** [comment]
@LukeTowers yes, this pr fixed my issue, for temporary fix i had have to use @lasat repo, and now all test pass.
It`s really a typo, because you can see correct name of the same method in this file below, [here](https://github.com/octobercms/library/blob/master/src/Html/UrlServiceProvider.php#L43) and [here](https://github.com/octobercms/library/blob/master/src/Html/UrlServiceProvider.php#L47). So it`s just a typo.

**Comment by NemoD503** [comment]
@LukeTowers I've made pr with [demonstration](https://github.com/NemoD503/october/pull/1). Just replace policy to force and all test will fail.

**Comment by LukeTowers** [comment]
@NemoD503 thanks! @lasat great job on spotting this!

**Pull request merged**
