### PR TITLE
Func Limit bugfix

### PR DESCRIPTION
**Pull request by reg2005**
There were [problems](https://github.com/octobercms/october/issues/1971) with Unicode

### CODE REVIEW

**Comment by daftspunk** [comment]
Hey @reg2005, sorry for the delay. This will be accepted, please resubmit to the `develop` branch.

**Comment by cracki** [comment]
this pull request not merged and the bug exists

**Comment by LukeTowers** [comment]
@daftspunk I submitted a PR with this change to the correct branch so that we can get this merged.

**Comment by daftspunk** [comment]
Fixed by #243

**Pull request closed without merging**
