### PR TITLE
Get for Height and Width and Resize images on upload to default maxWidht and Heigth 

### PR DESCRIPTION
**Pull request by estudiogenius**
Now ... we can specify some settings for sending images to Storage in config / cms.php as follows:
    'storage' => [
        'uploads' => [
            'disk'   => 'local',
            'folder' => 'uploads',
            'path'   => '/storage/app/uploads',
            'image'  => [
                'maxWidth' => 1900,
                'maxWHeight' => 1200,
                'quality' => 85,
            ],
        ],
...
PS: this update will not change the default config file...

### CODE REVIEW

**Comment by pedromazala** [comment]
+1

**Comment by wilcorrea** [comment]
+1

**Comment by Belluzzo** [comment]
+1

**Comment by daftspunk** [comment]
This manipulates every image upload? I'm not sure why this is necessary, this functionality should be introduced as a plugin with a simple event used here instead.

**Pull request closed without merging**
