### PR TITLE
Add get_class_methods() equivalent for extendable classes

### PR DESCRIPTION
**Pull request by bennothommo**
Adds a function to list all class methods (including those provided by an extension) to a class using the Extendable trait.

### CODE REVIEW

**Comment by LukeTowers** [comment]
Perfect! Do you feel like adding a unit test for this?

**Comment by LukeTowers** [comment]
Also it would be great if this was added to the docs along with methodExists (if not already present)

**Comment by bennothommo** [comment]
@LukeTowers unit tests now in place.
Docs PR is here: https://github.com/octobercms/docs/pull/354

**Comment by LukeTowers** [comment]
@bennothommo this is fantastic as usual, thanks!

**Pull request merged**
